export const DOMAINS = [
    "Gaming",
    "Programming & Technology",
    "Artificial Intelligence",
    "Education & Learning",
    "Science",
    "Health & Medicine",
    "Fitness & Wellness",
    "Sports",
    "Art & Design",
    "Music",
    "Movies & TV",
    "Books & Literature",
    "Writing",
    "Photography",
    "Videography & Filmmaking",
    "Performing Arts",
    "Food & Cooking",
    "Travel",
    "Nature & Outdoors",
    "Vehicles & Transportation",
    "Home & Lifestyle",
    "Business & Entrepreneurship",
    "Finance & Investing",
    "Shopping & Fashion",
    "Animals & Pets",
    "Culture & Languages",
    "History",
    "Religion & Spirituality",
    "Social & Community",
    "Relationships & Family",
    "Events & Entertainment",
    "Hobbies & Crafts",
    "Self Improvement",
    "Environment & Sustainability",
    "News & Politics",
    "Law & Government",
    "Space & Astronomy",
    "DIY & Maker",
    "Parenting",
    "General",
];
